version: "3.6" 
services:
  dlna-movies:
    image: sego/minidlna-armhf:stable
    networks: 
      pubnet:
        ipv4_address: 192.168.1.201
    volumes: 
      - type: bind
        source: ${MOVIES_DIR}
        target: /media
        read_only: true
    environment: 
      - MINIDLNA_media_dir=V,/media
      - MINIDLNA_friendly_name=Фильмы
    restart: always
  dlna-photos:
    image: sego/minidlna-armhf:stable
    networks: 
      pubnet:
        ipv4_address: 192.168.1.202
    volumes: 
      - type: bind
        source: ${PHOTOS_DIR}
        target: /media
        read_only: true
    environment: 
      - MINIDLNA_media_dir=PV,/media
      - MINIDLNA_friendly_name=Фото
    restart: always
  torrent:
    image: lsioarmhf/transmission:latest
    volumes: 
      - type: bind
        source: ${MOVIES_DIR}
        target: /downloads
        read_only: false
      - type: bind
        source: ${SYS_DIR}/transmission-daemon
        target: /config
        read_only: false
    environment: 
      - PUID=1000
      - PGID=1000
      - TRUSER=transmission
      - TRPASSWD=transmission
    networks: 
      pubnet:
        ipv4_address: 192.168.1.203
    restart: always
networks:
  pubnet:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
