version: "3.6" 
services:
  dlna-movies:
    image: sego/minidlna-armhf:stable
    net: pubnet
    volumes: 
      - /mnt/storage1/Media/Movies:/media:ro
    environment: 
      - MINIDLNA_media_dir=V,/media
      - MINIDLNA_FRIENDLY_NAME="NAS Фильмы"
  dlna-photos:
    image: sego/minidlna-armhf:stable
    net: pubnet
    volumes: 
      - /mnt/storage1/Media/Photos:/media:ro
    environment: 
      - MINIDLNA_media_dir=V,/media
      - MINIDLNA_FRIENDLY_NAME="NAS Фото"
networks:
  pubnet:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: pubnet
      config:
        subnet:  10.103.0.1/16
        gateway: 172.28.5.254
    
    