version: "3.6" 
services:
  dlna-movies:
    image: sego/minidlna-armhf:stable
    networks: 
      - pubnet
    volumes: 
      - type: bind
        source: /mnt/storage1/Media/Movies
        target: /media
        read_only: true
    environment: 
      - MINIDLNA_media_dir=V,/media
      - MINIDLNA_FRIENDLY_NAME="NAS Фильмы"
    restart: always
  dlna-photos:
    image: sego/minidlna-armhf:stable
    networks: 
      - pubnet
    volumes: 
      - type: bind
        source: /mnt/storage1/Media/Photos
        target: /media
        read_only: true
    environment: 
      - MINIDLNA_media_dir=PV,/media
      - MINIDLNA_FRIENDLY_NAME="NAS Фото"
    restart: always
networks:
  pubnet:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
