version: "3.6" 
services:
  dlna_movies:
    image: sego/minidlna-armhf:stable
    net: pub-net
    volumes: 
      - /mnt/storage1/Media/Movies:/media:ro
  dlna_photos:
    image: sego/minidlna-armhf:stable
    net: pub-net
    volumes: 
      - /mnt/storage1/Media/Photos:/media:ro
 networks:
   pub-net:
     driver: macvlan