version: "3.6" 
services:
  dlna-movies:
    image: sego/minidlna-armhf
    networks: 
      pubnet:
        ipv4_address: 192.168.1.201
    volumes: 
      - type: bind
        source: ${MOVIES_DIR}
        target: /media
        read_only: true
      - type: bind
        source: ${SYS_DIR}/dlna-movies-db
        target: /db
    environment: 
      - MINIDLNA_media_dir=V,/media
      - MINIDLNA_friendly_name=Фильмы
    restart: always
  dlna-photos:
    image: sego/minidlna-armhf
    networks:
      pubnet:
        ipv4_address: 192.168.1.202
    volumes: 
      - type: bind
        source: ${PHOTOS_DIR}
        target: /media
        read_only: true
      - type: bind
        source: ${SYS_DIR}/dlna-photos-db
        target: /db
    environment: 
      - MINIDLNA_media_dir=PV,/media
      - MINIDLNA_friendly_name=Фото
    restart: always
  bittorrent:
    image: lsioarmhf/transmission:latest
    volumes: 
      - type: bind
        source: ${MOVIES_DIR}
        target: /downloads
        read_only: false
      - type: bind
        source: ${SYS_DIR}/transmission-daemon
        target: /config
        read_only: false
    environment: 
      - PUID=1000
      - PGID=1000
    networks: 
      pubnet:
        ipv4_address: 192.168.1.203
    restart: always
  tor:
    image: sego/tor-armhf
    networks: 
      pubnet:
        ipv4_address: 192.168.1.204
    restart: always
  nginx:
    image: arm32v7/nginx:1.15
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./www
        target: /data/www
        read_only: true
    networks: 
      pubnet:
        ipv4_address: 192.168.1.210
    restart: always
networks:
  pubnet:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
